### ISSUE TITLE
Darkweb-everywhere extension

### ISSUE THREAD

**Issue by cmahns** [chris-barry/darkweb-everywhere#21]
As you may know, Chris and myself have decided to move forward with forking HTTPS-Everywhere into an extension that can be loaded into the Tor Browser. We feel it is easier to tell an end user to drag and drop an extension into TBB, rather than explain that they need to run a script or copy an entire folder. 

There are some bugs we know of already and are planning on (hopefully) fixing. Right now due to some reorganizing, the current install scripts and documentation is broken/out of date for the time being. But that can be fixed once either of us find time. 

Any questions, enhancements, ideas, or insults? Put them here :)

**Comment by bugreport0** [comment]
Why all I2P rules are disabled by default, I want for example I2P rules only, not Tor - with .zip file in few seconds I could copy interesting rules. Now I have to unpack source (unpacking hundreds of files takes a while), find interesting rules, copy them, and enable in HTTPS Everywhere's options. When I want only Tor rulesets, I still need to delete some non-onion rules with "onion" in name!

The webpage displays misleading information: "HTTPS EVERYWHERE RULESETS", but when I click I have extension!

Is it so hard to provide both extension and rulesets (in 2 folders, all enabled by default - excepting unconfirmed of course) in .zip file?

**Comment by chris-barry** [comment]
bugreport0: They are disabled because this is primarially meant to be used with the tor browser bundle. There are a few problems with having tor and i2p rules on at the same time. First, if someone does not have i2p installed and running, this would cause a lot of dead links. Secondly, many sites have tor and i2p sites. With both running, how would a priority be set?

To get the i2p rules, you can download the source code and `ls eep*.xml`.
