### ISSUE TITLE
http://ftp.debian.org has a onion URL

### ISSUE THREAD

**Issue by qbi** [chris-barry/darkweb-everywhere#37]
The site http://ftp.debian.org/ has now the following onion URL: http://vwakviie2ienjx6t.onion/
See http://richardhartmann.de/blog/posts/2015/08/24-Tor-enabled_Debian_mirror/

Please add this as a ruleset.

**Comment by colinmahns** [comment]
Added! https://github.com/chris-barry/darkweb-everywhere/commit/e7f60bb28a1562270bbfa60ad66eba5d250ec509

I've put this one in the disabled state as it's *technically* transferring ownership, something we try to not do with our rules. I'm willing to mark it otherwise due to the site's content but would need further discussion with @chris-barry.

**Comment by chris-barry** [comment]
+1 for disabled. This is cool, but I don't want to accidentally redirect everyone who was expecting to go to ftp.debian.org *if* this isn't ran by Debian.

**Comment by colinmahns** [comment]
I don't think a redirect would be that harmful in this example (assuming the HS stays up, something that might happen as per the blog). If a malicious actor modifies the content on a page and a user downloads it, apt is going to start screaming due to it not matching the approved keys that Debian signs their packages with. It's not as malicious as some of the other rules we have in this case. 

I'm for having this one instance being the exception to our rule, provided they figure out the hosting situation.
